version: '3.2'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config:/etc/nginx/
      - ./nginx/certs:/usr/share/certs
      - ./nginx/html:/var/www
      - ./jess-portfolio:/usr/share/nginx/jess-portfolio
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./nginx/certs:/etc/letsencrypt
  #     - ./nginx/html:/var/www
  #   command: [ "renew" ]
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     restart_policy:
  #       condition: any
  #       delay: 86400s
  #       window: 120s


  ghost:
    image: ghost:latest
    volumes:
      - ghost_source_demo:/usr/src/ghost
      - ghost_content_demo:/var/lib/ghost
      - ./ghost/config.js:/var/lib/ghost/config.js
      - ../ABitMoreDepthTheme:/var/lib/ghost/themes/abmd

    ports:
      - "2368:2368"
    command: [
      "npm",
      "start",
      "--development"
      ]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  mariadb:
    image: mariadb:latest
    volumes:
      - maria_data_demo:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=Holyfeckthisisoneofthosereallydamnablylongrootpasswords!!"
      - "MYSQL_DATABASE=ghost"
      - "MYSQL_USER=ghostly"
      - "MYSQL_PASSWORD=ahnonotanotheroneofthosereallybastardlongpasswords..?"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

volumes:
  maria_data_demo:

  ghost_source_demo:

  ghost_content_demo:
