version: '3.2'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config:/etc/nginx/
      - ./nginx/certs:/usr/share/certs
      - ./jess-portfolio:/usr/share/nginx/jess-portfolio
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  ghost:
    image: ghost:latest
    volumes:
      - ghost_source:/usr/src/ghost
      - ghost_content:/var/lib/ghost
      - ./ghost/config.js:/var/lib/ghost/config.js
    ports:
      - "2368:2368"
    command: [
      "npm",
      "start",
      "--production"
      ]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  mariadb:
    image: mariadb:latest
    volumes:
      - maria_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=Holyfeckthisisoneofthosereallydamnablylongrootpasswords!!"
      - "MYSQL_DATABASE=ghost"
      - "MYSQL_USER=ghostly"
      - "MYSQL_PASSWORD=ahnonotanotheroneofthosereallybastardlongpasswords..?"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

volumes:
  maria_data:

  ghost_source:

  ghost_content:
