version: '3'

services:
  nginx:
    build:
      context: .
    # volumes:
    #   - ./static:/usr/share/nginx/static
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        
