---
version: '3.2'

services:
  ci:
    build:
      context: jenkins/master
      dockerfile: Dockerfile
    image: registry.abitmoredepth.com/ci-master:latest
    user: root:users
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone:ro
      - type: bind
        source: /usr/share/zoneinfo/${TZ:-Europe/London}
        target: /usr/share/zoneinfo/${TZ:-Europe/London}
      - type: bind
        source: /usr/share/zoneinfo/${TZ:-Europe/London}
        target: /etc/localtime
      - "/var/run/docker.sock:/var/run/docker.sock:z"
      - "./ci/jobs:/var/jenkins_home/jobs"
      - "./ci/workspace:/var/jenkins_home/workspace"
    environment:
      - TZ=${TZ:-Europe/London}
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"
    networks:
      - main
    secrets:
      - ci-user
      - ci-password
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=jenkins"
        - "traefik.docker.network=abitmoredepth_main"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=Host:ci.abitmoredepth.com"
        - "traefik.port=8080"

  ghost:
    image: ghost:latest
    volumes:
      - ./ghost/config.production.json:/var/lib/ghost/config.production.json
      - ghost_content:/var/lib/ghost/content
    environment:
      - "database__client:mariadb"
      - "database__connection__host:mariadb"
      - "database__connection__user:ghostly"
      - "database__connection__password:ahnonotanotheroneofthosereallybastardlongpasswords..?"
      - "database__connection__database:ghost"
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=ghost"
        - "traefik.docker.network=abitmoredepth_main"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=Host:www.abitmoredepth.com,abitmoredepth.com"
        - "traefik.port=2368"

  mariadb:
    image: mariadb:5
    volumes:
      - maria_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=Holyfeckthisisoneofthosereallydamnablylongrootpasswords!!"
      - "MYSQL_DATABASE=ghost"
      - "MYSQL_USER=ghostly"
      - "MYSQL_PASSWORD=ahnonotanotheroneofthosereallybastardlongpasswords..?"
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager

  portainer:
    image: portainer/portainer
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer-data
        target: /data
    networks:
      - main
      - portainer_agent
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=portainer"
        - "traefik.docker.network=abitmoredepth_main"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=Host:manage.abitmoredepth.com"
        - "traefik.port=9000"

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  registry:
    image: registry:2
    volumes:
      - type: volume
        source: reg-data
        target: /var/lib/registry
      - type: bind
        source: ./registry/reg-config.yaml
        target: /etc/docker/registry/config.yml
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=registry"
        - "traefik.docker.network=abitmoredepth_main"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.redirect.entrypoint=https"
        - "traefik.frontend.rule=Host:registry.abitmoredepth.com"
        - "traefik.port=5000"

  regUI:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_USE_SSL=0
      - ENV_MODE_BROWSE_ONLY=false
    depends_on:
      - registry
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.backend=docker-registry-ui"
        - "traefik.docker.network=abitmoredepth_main"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=Host:reg-ui.abitmoredepth.com"
        - "traefik.port=80"

  traefik:
    image: traefik
    build:
      context: traefik/
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/certs:/etc/traefik/acme/
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=traefik"
        - "traefik.docker.network=abitmoredepth_main"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=Host:traefik.abitmoredepth.com"
        - "traefik.port=8080"

volumes:
  ghost_content:

  ghost_source:

  maria_data:

  portainer-data:

  reg-data:

networks:
  portainer_agent:
    driver: overlay
    attachable: true

  main:
    driver: overlay
    attachable: true

secrets:
  ci-user:
    file: ./jenkins/master/secret-user
  ci-password:
    file: ./jenkins/master/secret-password
